apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rabbit-server-container
          image: rabbit-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_USERNAME
              value: "<username>"
            - name: RABBITMQ_PASSWORD
              value: "<password>"
            - name: RABBITMQ_SERVICE
              value: "rabbit-mq-cluster"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: consumer-container
          image: consumer:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_USERNAME
              value: "<username>"
            - name: RABBITMQ_PASSWORD
              value: "<password>"
            - name: RABBITMQ_SERVICE
              value: "rabbit-mq-cluster"